# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  
  # provision config with ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible.playbook"
  end
end
